services:
  nextjs:
    build: .
    container_name: lulai-chatbot-platform
    restart: always
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@lulai-db:5432/chatbot"
      NEXTAUTH_URL: "http://localhost:3001"
      NEXTAUTH_SECRET: "6fbbJ2rDi+mCPnBefneSAdy0VZgxAHFw/81l/TlQMhs="
      EMAIL_HOST: "smtp.gmail.com"
      EMAIL_PORT: "587"
      EMAIL_USER: "britotiago101@gmail.com"
      EMAIL_PASSWORD: "fzib rizt sqah kmak"
      EMAIL_FROM: "britotiago101@gmail.com"
      ADMIN_CREATE_TOKEN: "B38QD/6K2u5xk0Jie0Brf4zB9KfNFxdex88e47Mp6Bc="
      GOOGLE_CLIENT_ID: "743857672562-dlkqv5hatpihubmabftse6nsi3q0po7l.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51QzSlhJkXSsnTAnudTTHKbYwCBYr2oUPWgmDv63iiZhyzFCAgYciho4xO1ohZz4lDzUbilfr9asgHX5D66Jh6w2Q00VGQBARi8"
      STRIPE_SECRET_KEY: "sk_test_51QzSlhJkXSsnTAnuMGfUTh8vy4qwrKIJXe9GnO0dG6XcaJkrAJ6fJK4JKiq1iQvuWCLFeC5SV7CxsbgoIb7Ut7gN00NaU7jWt7"
      STRIPE_PUBLISHABLE_KEY: "pk_test_51QzSlhJkXSsnTAnudTTHKbYwCBYr2oUPWgmDv63iiZhyzFCAgYciho4xO1ohZz4lDzUbilfr9asgHX5D66Jh6w2Q00VGQBARi8"
      ADMIN_NAME: "Tiago Brito"
      ADMIN_EMAIL: "britotiago123@gmail.com"
    networks:
      - chatbot_network
      - database_network  # Join the database network

networks:
  chatbot_network:
    driver: bridge
  database_network:  # Reference the external network created by database-compose
    external: true
    name: chatbot_db_network