version: '3.8'

services:
  postgres:
    image: postgres:15.0
    container_name: chatbot_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot_platform_db  # Docker creates this automatically
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Runs only if DB is empty

  nextjs:
    build: .
    container_name: chatbot_nextjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/chatbot_platform_db"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: