services:
  postgres:
    image: postgres:latest
    container_name: chatbot
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot  # Docker creates this automatically
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Runs only if DB is empty

  nextjs:
    build: .
    container_name: nextjs_app1
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      #DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/ecommerce_db1"
      DATABASE_URL: "postgresql://postgres:postgres@lulai-chatbot-db:5432/chatbot"

volumes:
  postgres_data:
