services:
  nextjs:
    build: .
    container_name: lulai-chatbot-platform
    restart: always
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@lulai-db:5432/lulai?options=--search_path%3Dchatbot_schema"
      NEXTAUTH_URL: "http://localhost:3001"
      NEXTAUTH_SECRET: "6fbbJ2rDi+mCPnBefneSAdy0VZgxAHFw/81l/TlQMhs="
      EMAIL_HOST: "smtp.gmail.com"
      EMAIL_PORT: "587"
      EMAIL_USER: "britotiago101@gmail.com"
      EMAIL_PASSWORD: "fzib rizt sqah kmak"
      EMAIL_FROM: "britotiago101@gmail.com"
      ADMIN_CREATE_TOKEN: "B38QD/6K2u5xk0Jie0Brf4zB9KfNFxdex88e47Mp6Bc="
      GOOGLE_CLIENT_ID: "743857672562-dlkqv5hatpihubmabftse6nsi3q0po7l.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51QzSlhJkXSsnTAnudTTHKbYwCBYr2oUPWgmDv63iiZhyzFCAgYciho4xO1ohZz4lDzUbilfr9asgHX5D66Jh6w2Q00VGQBARi8"
      STRIPE_SECRET_KEY: "sk_test_51QzSlhJkXSsnTAnuMGfUTh8vy4qwrKIJXe9GnO0dG6XcaJkrAJ6fJK4JKiq1iQvuWCLFeC5SV7CxsbgoIb7Ut7gN00NaU7jWt7"
      STRIPE_PUBLISHABLE_KEY: "pk_test_51QzSlhJkXSsnTAnudTTHKbYwCBYr2oUPWgmDv63iiZhyzFCAgYciho4xO1ohZz4lDzUbilfr9asgHX5D66Jh6w2Q00VGQBARi8"
      ADMIN_NAME: "Tiago Brito"
      ADMIN_EMAIL: "britotiago101@gmail.com"
      API_URL: "http://localhost:3001"
      NEXT_PUBLIC_APP_URL: "http://localhost:3001"
      NEXT_PUBLIC_CHATBOT_URL: "http://localhost:3005"
      CHATBOT_SERVICE_URL: "http://lulai-chatbot-service:3000"
      OPENAI_API_KEY: "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"
    networks:
      - database_network

networks:
  database_network:
    external: true
    name: lulai_db_network








