services:
  postgres:
    image: postgres:latest
    container_name: lulai-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Updated path to match your structure
    networks:
      - database_network

networks:
  database_network:
    name: chatbot_db_network
    driver: bridge

volumes:
  postgres_data: