
services:
  nextjs:
    build: .
    container_name: chatbot
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - ./scripts:/scripts
    command: ["npm", "run", "dev"]
    depends_on:
      - python-server # Ensure python server starts before nextjs

  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    container_name: python_server
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend # Can be any custom network name
    expose:
      - "8000" # Exposes port internally to other services

networks:
  backend:
    driver: bridge
