services:
  nextjs:
    build: .
    container_name: lulai-ecommerce-store
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@lulai-db:5432/lulai?options=--search_path%3Decommerce_schema"
      EMAIL_HOST: "smtp.gmail.com"
      EMAIL_PORT: "587"
      EMAIL_SECURE: "false"
      EMAIL_USER: "britotiago101@gmail.com"
      EMAIL_PASSWORD: "fzib rizt sqah kmak"
      EMAIL_FROM: "britotiago101@gmail.com"
      EMAIL_FROM_NAME: "ecommerce"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "7e34fa6e0dd0b5c60fdcb2fd9ea75f52ef87cdde6eb5a5d2"
      API_URL: "http://localhost:3000"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51QzSlhJkXSsnTAnudTTHKbYwCBYr2oUPWgmDv63iiZhyzFCAgYciho4xO1ohZz4lDzUbilfr9asgHX5D66Jh6w2Q00VGQBARi8"
      STRIPE_SECRET_KEY: "sk_test_51QzSlhJkXSsnTAnuMGfUTh8vy4qwrKIJXe9GnO0dG6XcaJkrAJ6fJK4JKiq1iQvuWCLFeC5SV7CxsbgoIb7Ut7gN00NaU7jWt7"
      STRIPE_PUBLISHABLE_KEY: "pk_test_51QzSlhJkXSsnTAnudTTHKbYwCBYr2oUPWgmDv63iiZhyzFCAgYciho4xO1ohZz4lDzUbilfr9asgHX5D66Jh6w2Q00VGQBARi8"
      OPENAI_API_KEY: "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"
      TTS_API_KEY: "sk_45f83853ba87af0df3819ef2e727a9fc018c0c18fa0e4f0a"
      TTS_API_URL: "https://api.elevenlabs.io/v1/text-to-speech"
      TTS_VOICE_ID: "ErXwobaYiN019PkySvjV"
      NEXT_PUBLIC_TTS_API_URL: "http://localhost:8001/tts"
      NEXT_PUBLIC_STT_API_URL: "http://localhost:8001/whisper"
      ADMIN_EMAIL: "britotiago123@gmail.com"
    networks:
      - database_network

networks:
  database_network:
    external: true
    name: lulai_db_network


