services:
  postgres:
    image: postgres:15.0
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_db  # Docker creates this automatically
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Runs only if DB is empty

  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/ecommerce_db"

volumes:
  postgres_data:
