services:
  postgres:
    image: postgres:15.0
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_db  # Docker creates this automatically
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Runs only if DB is empty

  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/ecommerce_db"
      EMAIL_HOST: "smtp.gmail.com"
      EMAIL_PORT: "587"
      EMAIL_SECURE: "false"
      EMAIL_USER: "britotiago101@gmail.com"
      EMAIL_PASSWORD: "fzib rizt sqah kmak"
      EMAIL_FROM: "britotiago101@gmail.com"
      EMAIL_FROM_NAME: "ecommerce"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "7e34fa6e0dd0b5c60fdcb2fd9ea75f52ef87cdde6eb5a5d2"
      API_URL: "http://localhost:3000"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51QzSlhJkXSsnTAnudTTHKbYwCBYr2oUPWgmDv63iiZhyzFCAgYciho4xO1ohZz4lDzUbilfr9asgHX5D66Jh6w2Q00VGQBARi8"
      STRIPE_SECRET_KEY: "sk_test_51QzSlhJkXSsnTAnuMGfUTh8vy4qwrKIJXe9GnO0dG6XcaJkrAJ6fJK4JKiq1iQvuWCLFeC5SV7CxsbgoIb7Ut7gN00NaU7jWt7"
      STRIPE_PUBLISHABLE_KEY: "pk_test_51QzSlhJkXSsnTAnudTTHKbYwCBYr2oUPWgmDv63iiZhyzFCAgYciho4xO1ohZz4lDzUbilfr9asgHX5D66Jh6w2Q00VGQBARi8"
      OPENAI_API_KEY: "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"
      TTS_API_KEY: "sk_45f83853ba87af0df3819ef2e727a9fc018c0c18fa0e4f0a"
      TTS_API_URL: "https://api.elevenlabs.io/v1/text-to-speech"
      TTS_VOICE_ID: "ErXwobaYiN019PkySvjV"
      ADMIN_EMAIL: "britotiago101@gmail.com"



volumes:
  postgres_data:
