services:
  nextjs:
    build: .
    container_name: lulai-chatbot-service
    restart: always
    ports:
      - "3005:3000"
    environment:
      OPENAI_API_KEY: "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"
      NEXT_PUBLIC_PYTHON_SERVER_URL: "http://localhost:8001/"
      NEXT_PUBLIC_API_KEY: "f70d5dc9b2324bbb4bd8e31cde172222"
      DATABASE_URL: "postgresql://postgres:postgres@lulai-db:5432/lulai?options=--search_path%3Dchatbot_schema"
    volumes:
      - .:/app
      - /app/node_modules
      - ./scripts:/scripts
    networks:
      - lulai_db_network
    command: ["npm", "run", "dev"]
    depends_on:
      - python-server # Ensure python server starts before nextjs

  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    container_name: lulai-python-server
    restart: always
    ports:
      - "8001:8000"
    environment:
      OPENAI_API_KEY: "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"
      ELEVENLABS_API_KEY: "sk_32e81a4e50ca74689fb1cbcdf7be41fa76a7aad6d8de4898"
      TTS_API_URL: "https://api.elevenlabs.io/v1/text-to-speech"
      TTS_VOICE_ID: "ErXwobaYiN019PkySvjV"
    networks:
      - lulai_db_network
    volumes:
      - ./python-server:/app
    expose:
      - "8000"

networks:
  lulai_db_network:
    external: true